Front end options
DELTA-GLOW-2023/glow-2023-frontend pull request #14
Opened 2023-06-09 09:12 UTC by DewiKimC

- Changed switch statement to individual pages
- Added cookies, so it won't be possible to have the same prompt as the person before you
- Added End screen

2023-06-10 11:52 UTC, BartvanEijkelenburg requested changes

2023-06-10 11:52 UTC, BartvanEijkelenburg commented on jsconfig.json
> +{
I think this file can be deleted.

2023-06-10 11:52 UTC, BartvanEijkelenburg commented on package.json
> +    "react-cookie": "^4.1.1",
I would remove this package and use the localStorage instead. Since cookies are intended for a different use. (Server communication and such).

2023-06-10 11:52 UTC, BartvanEijkelenburg commented on src/pages/InputPage.tsx
> +    cookies.set("lastPrompt", prompt, { path: "/" })
```suggestion
    localStorage.setItem("lastPrompt", prompt)
```
[Link to localStorage API info](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)

2023-06-10 11:52 UTC, BartvanEijkelenburg commented on package.json
> +    "react-cookie": "^4.1.1",
<img width="792" alt="image" src="https://github.com/DELTA-GLOW-2023/glow-2023-frontend/assets/73314842/c0ef7cbf-ca1b-426b-b32f-2fb82f03ef85">

2023-06-10 11:52 UTC, BartvanEijkelenburg commented on src/pages/StartPage.tsx
> +        <Link to="/input">
This is a working solution. No need to change :).

For info: for this application we could also use the navigate function // hook. 

From the react-router-dom package.

2023-10-12 07:48 UTC, BartvanEijkelenburg commented on src/components/core/Carousel.tsx
> +                    </svg>
Extract these svg's into smaller components, so we now what the icon is:

For instance this one: BackIcon

2023-10-12 07:48 UTC, BartvanEijkelenburg commented on src/components/core/Carousel.tsx
> +                    </svg>
Extract svg to component

2023-10-12 07:48 UTC, BartvanEijkelenburg commented on src/pages/InputPage.tsx
> +    // texAREA ELEMENT class h-40 add
What's this?

2023-10-12 07:48 UTC, BartvanEijkelenburg commented on src/pages/InputPage.tsx
> +                          </svg>
Extract this error SVG aswell.

2023-10-12 07:53 UTC, BartvanEijkelenburg approved these changes

2023-10-12 07:53 UTC, BartvanEijkelenburg commented on src/components/core/Carousel.tsx
> +          </svg>
Extract Component

2023-10-12 07:53 UTC, BartvanEijkelenburg commented on src/pages/InputPage.tsx
> +                          </svg>
Extract component

2023-10-12 07:53 UTC, BartvanEijkelenburg commented on src/components/core/Carousel.tsx
> +          </svg>
Extract

2023-10-12 07:53 UTC, BartvanEijkelenburg requested changes
Fix Comments above pls :)

2023-10-23 07:51 UTC, Jasper123pyah approved these changes

2023-10-23 07:54 UTC, Jasper123pyah approved these changes

2023-10-23 07:54 UTC, BartvanEijkelenburg approved these changes

2023-10-23 07:54 UTC, merged